import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const out=process.env.UNIFLEET_QA_OUTPUT||new URL('../../../../qa/docking-20261009/',import.meta.url).pathname;const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1600,height:1000},timezoneId:'Asia/Kolkata'});const results=[],errors=[],failedApis=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes(':4228')&&r.status()>=400)failedApis.push({url:new URL(r.url()).pathname,status:r.status()});});
await page.goto('http://127.0.0.1:5198');await page.getByLabel('Name',{exact:true}).fill('AI Dock Review');await page.getByLabel('Email',{exact:true}).fill('ai-dock-review@example.com');await page.getByRole('button',{name:'Continue to UniFleet'}).click();await expect(page.getByRole('navigation',{name:'Main navigation'})).toBeVisible();
await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Live Operations',exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/operations/control-tower/import'));await page.getByRole('button',{name:'Import schedule workbook'}).click();const runs=(await(await response).json()).runs;const stale=runs.find(r=>r.schedule.origin_station==='UDRPU'&&r.schedule.mode==='SURFACE');await page.evaluate(async run=>{const {useControlTowerStore}=await import('/src/store/controlTowerStore.ts');useControlTowerStore.getState().select(run);},stale);await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'AI Chat',exact:true}).click();
const workspace=()=>page.locator('.dockable-workspace:visible').first();const panel=()=>workspace().getByLabel('Map panel',{exact:true});
async function dock(position){await panel().getByLabel('Map layout menu').click();await panel().getByRole('button',{name:'Dock '+position,exact:true}).click();await expect(workspace()).toHaveAttribute('data-dock-position',position);}
async function send(message){const input=page.locator('.workspace-chat-drawer:visible textarea');await input.fill(message);const response=page.waitForResponse(r=>r.url().endsWith('/mcp-agent'),{timeout:30000});await input.press('Enter');const data=await(await response).json();expect(data.success).toBe(true);expect(data.response).not.toContain('UDRPU');return data;}
const messages=['What services are available from CJBMB to BLRGW?','Show me the Air option.','Show me the Surface option.','What is the ETD and ETA of flight 6E 5355?','Which option arrives first?','Which vehicle is assigned to the Surface service from CJBMB to BLRGW?','What is its capacity?','Plan 2000 kg from CJBMB to BLRGW.','What happens if the shipment becomes 4000 kg?','Which available option can carry it?','Show the capacity and utilization calculation.','Which option from CJBMB to BLRGW is cheapest?','Delay the CJBMB-BLRGW Surface run by 30 minutes.','What is the revised ETA?','The Surface vehicle has broken down. Find a replacement.','6E 5355 ka ETA kya hai?','CJBMB se BLRGW ke liye kya services hain?','6E 5355 की ETA क्या है?','अगर Surface vehicle breakdown हो जाए तो क्या option है?'];
for(let i=0;i<messages.length;i++){
 try{const data=await send(messages[i]);if(i===0||i===16)expect(data.services).toHaveLength(2);if([1,3,4,15,17].includes(i))expect(data.response).toContain('6E 5355');if(i===2)expect(data.response).toContain('TATA 407');if(i===5)expect(data.response).toContain('SUR-surface-25-01');if(i===6)expect(data.response).toContain('2,500');if(i===7)expect(data.planning_result.planning_request.shipment.weight_kg).toBe(2000);if(i===8)expect(data.planning_result.planning_request.shipment.weight_kg).toBe(4000);if(i===9){expect(data.response).toContain('NOT FEASIBLE');expect(data.capacity_results.find(r=>r.service_id==='air-11').feasible).toBe(true);}if(i===10)expect(data.response).toContain('4,000');if(i===11)expect(data.planning_result.planning_request.shipment.weight_kg).toBe(4000);if(i===12||i===13)expect(data.response).toContain('06:30 IST');if(i===14||i===18){expect(data.recovery.replacement_vehicles).toHaveLength(0);expect(data.response).toContain('No same-service spare');expect(data.response).toContain('6E 5355');}
 results.push({name:'Exact AI prompt '+(i+1),message:messages[i],pass:true,...data});console.log('PASS',i+1,messages[i]);}catch(e){results.push({name:'Exact AI prompt '+(i+1),message:messages[i],pass:false,error:e.message});console.log('FAIL',i+1,e.message.slice(0,300));}
}
for(const [position,message,needle] of [['right','What is the ETD and ETA of flight 6E 5355?','22:40 IST'],['left','Show me the Surface option.','TATA 407'],['top','Plan 2000 kg from CJBMB to BLRGW.','2,000'],['bottom','The Surface vehicle has broken down. Find a replacement.','No same-service spare']]){
 try{await dock(position);const data=await send(message);expect(data.response).toContain(needle);results.push({name:'AI with map '+position,message,pass:true,...data});console.log('PASS AI layout',position);}catch(e){results.push({name:'AI with map '+position,message,pass:false,error:e.message});console.log('FAIL AI layout',position,e.message.slice(0,300));}
}
await dock('left');await page.locator('.chat-messages:visible').evaluate(el=>el.scrollTop=el.scrollHeight);await new Promise(r=>setTimeout(r,500));await page.screenshot({path:out+'/14-ai-custom-layout.png'});await fs.writeFile(out+'/ai-results.json',JSON.stringify({results,errors,failedApis},null,2));await browser.close();if(results.some(r=>!r.pass)||errors.length||failedApis.length)process.exitCode=1;
