const out=process.env.UNIFLEET_QA_OUTPUT||new URL('../../../../qa/docking-20261009/',import.meta.url).pathname;
import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1280,height:900},timezoneId:'Asia/Kolkata'});const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5198');await page.getByLabel('Name',{exact:true}).fill('Dock Laptop Review');await page.getByLabel('Email',{exact:true}).fill('dock-laptop@example.com');await page.getByRole('button',{name:'Continue to UniFleet'}).click();await expect(page.getByRole('navigation',{name:'Main navigation'})).toBeVisible();
const workspace=()=>page.locator('.dockable-workspace:visible').first();const panel=()=>workspace().getByLabel('Map panel',{exact:true});async function dock(position){await panel().getByLabel('Map layout menu').click().catch(async e=>{await page.screenshot({path:out+'/laptop-failure.png'});console.log(await workspace().evaluate(el=>({root:el.getBoundingClientRect().toJSON(),panel:el.querySelector('.dock-map-panel').getBoundingClientRect().toJSON(),header:el.querySelector('.dock-map-header').getBoundingClientRect().toJSON(),css:el.getAttribute('style')})));throw e;});await panel().getByRole('button',{name:'Dock '+position,exact:true}).click();}
for(const name of ['Dashboard','Planning','Live Operations']){await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name,exact:true}).click();await expect(page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name,exact:true})).toHaveAttribute('aria-pressed','true');for(const position of ['left','right','top','bottom','floating']){console.log('CHECK',name,position);await dock(position);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(panel().locator('.leaflet-container')).toBeVisible();results.push({name:name+' laptop '+position,pass:true});}await dock('right');}
const response=page.waitForResponse(r=>r.url().endsWith('/operations/control-tower/import'));await page.getByRole('button',{name:'Import schedule workbook'}).click();const runs=(await(await response).json()).runs;const chosen=[runs.find(r=>r.schedule_id==='air-11'),runs.find(r=>r.schedule_id==='surface-25'),runs.find(r=>r.schedule.mode==='RAIL'),runs.find(r=>r.schedule.origin_station==='UDRPU'&&r.schedule.mode==='SURFACE')];for(let i=0;i<chosen.length;i++){const run=chosen[i];await page.getByRole('checkbox',{name:`Select route ${run.schedule.lane} ${run.schedule.service} Run ${run.schedule.run}`,exact:true}).check();await expect(page.locator('.multi-run-card')).toHaveCount(i+1);await expect(workspace().locator('.map-caption')).toContainText(`${i+1} of ${i+1} mapped`);results.push({name:'Laptop selected routes '+(i+1),pass:true});}
await dock('floating');await panel().getByRole('button',{name:'Expand map'}).click();await page.reload();await expect(workspace()).toHaveAttribute('data-maximized','true');await panel().getByRole('button',{name:'Restore map'}).click();await expect(workspace()).toHaveAttribute('data-dock-position','floating');results.push({name:'Floating maximize persistence and restore',pass:true});await panel().getByRole('button',{name:'Dock',exact:true}).click();
await page.setViewportSize({width:760,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);results.push({name:'Narrow stacked layout without horizontal overflow',pass:true});
await fs.writeFile(out+'/extra-results.json',JSON.stringify({results,errors},null,2));await browser.close();if(errors.length)process.exitCode=1;
