import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const out=process.env.UNIFLEET_QA_OUTPUT||new URL('../../../../qa/product-fixes-20261009/',import.meta.url).pathname;await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1000},timezoneId:'Asia/Kolkata'});
const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
const shot=async(name)=>{await page.locator('.leaflet-tile-loaded').first().waitFor({state:'visible',timeout:1500}).catch(()=>{});await new Promise(resolve=>setTimeout(resolve,650));await page.locator('.chat-messages').evaluateAll(nodes=>nodes.forEach(node=>{node.scrollTop=node.scrollHeight;}));await page.screenshot({path:out+'/'+name+'.png',fullPage:true});};
async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message.slice(0,400));await shot('failure-'+results.length);}}
const nav=async(name)=>{const button=page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name,exact:true});await button.click();if(name!=='AI Chat')await expect(button).toHaveAttribute('aria-pressed','true');};
async function api(url,data,method='get'){return page.evaluate(async({url,data,method})=>{const {default:client}=await import('/src/api/client.ts');return (await client.request({url,data,method})).data;},{url,data,method});}
async function selectLocation(label,query,code){const input=page.getByRole('combobox',{name:label,exact:true});await input.fill(query);await page.getByRole('option').filter({hasText:code}).first().click();}
let model,runs;
await check('Dashboard labels',async()=>{await page.goto('http://127.0.0.1:5198');await page.getByLabel('Name',{exact:true}).fill('Product Fix Review');await page.getByLabel('Email',{exact:true}).fill('product-browser-review@example.com');await page.getByRole('button',{name:'Continue to UniFleet'}).click();await expect(page.getByRole('navigation',{name:'Main navigation'})).toBeVisible();await expect(page.getByLabel('Network overview')).toContainText('320');model=await api('/client-network');await shot('01-dashboard');});
let mapIdentity;
await check('Planning right map and name/code selection',async()=>{await nav('Planning');await expect(page.locator('.planning-chat-drawer')).toHaveCount(0);const boxes=await page.evaluate(()=>{const a=document.querySelector('.planning-left').getBoundingClientRect(),b=document.querySelector('.planning-map').getBoundingClientRect();return {left:{x:a.x,width:a.width,y:a.y},map:{x:b.x,width:b.width,y:b.y}};});expect(Math.abs(boxes.left.width-boxes.map.width)).toBeLessThan(10);expect(boxes.map.x).toBeGreaterThan(boxes.left.x);expect(boxes.map.y).toBe(boxes.left.y);await page.evaluate(()=>{document.querySelector('.planning-map .leaflet-container').dataset.qaIdentity='persistent';});await selectLocation('Source','Coimbatore','CJBMB');await selectLocation('Destination','Bengaluru','BLRGW');await page.getByRole('spinbutton',{name:'Weight kg',exact:true}).fill('2000');const response=page.waitForResponse(r=>r.url().endsWith('/planning/plans'));await page.getByRole('button',{name:'Calculate Plan',exact:true}).click();expect((await(await response).json()).candidate_plans).toHaveLength(2);await shot('02-planning-split');});
await check('Resizable split and left chat',async()=>{const divider=page.getByRole('separator',{name:'Resize planning and map'});await divider.press('ArrowLeft');expect(Number(await divider.getAttribute('aria-valuenow'))).toBe(48);await divider.press('Home');await nav('AI Chat');await expect(page.locator('.planning-left .chat-panel')).toBeVisible();const p=await page.locator('.planning-map').boundingBox(),c=await page.locator('.planning-chat-drawer .resizable-pane').boundingBox();expect(c.x+c.width).toBeLessThanOrEqual(p.x);await shot('03-planning-left-chat');await page.getByRole('button',{name:'Close AI',exact:true}).click();});
await check('Schedules cutoff and next source template',async()=>{await page.getByRole('button',{name:'Schedules',exact:true}).click();await selectLocation('Origin Station','Coimbatore','CJBMB');await selectLocation('Gateway','Bengaluru','BLRGW');await page.getByLabel(/Shipment Ready Time/).fill('18:01');await page.getByRole('button',{name:'Evaluate Cutoffs'}).click();await expect(page.locator('.fedex-table')).toContainText('21:25');await expect(page.locator('.fedex-table')).toContainText('06:00');await expect(page.locator('.planning-map .leaflet-container')).toHaveAttribute('data-qa-identity','persistent');await shot('04-schedules');await page.getByLabel(/Shipment Ready Time/).fill('21:31');await page.getByRole('button',{name:'Evaluate Cutoffs'}).click();await expect(page.getByText(/Next supplied schedule template/)).toBeVisible();});
await check('Network searchable names and persistent map',async()=>{await page.getByRole('button',{name:'Network Overview',exact:true}).click();await expect(page.getByLabel('Network overview').locator('tbody tr')).toHaveCount(38);await page.getByLabel('Search network',{exact:true}).fill('Bengaluru');expect(await page.getByLabel('Network overview').locator('tbody tr').count()).toBeGreaterThan(0);await expect(page.getByLabel('Network overview')).toContainText('Coimbatore (CJBMB)');await expect(page.locator('.planning-map .leaflet-container')).toHaveAttribute('data-qa-identity','persistent');await shot('05-network-overview');});
await check('Live counts and source transport visuals',async()=>{await nav('Live Operations');const response=page.waitForResponse(r=>r.url().endsWith('/operations/control-tower/import'));await page.getByRole('button',{name:'Import schedule workbook'}).click();runs=(await(await response).json()).runs;await expect(page.locator('.operations-table tbody tr')).toHaveCount(38);expect(runs.filter(r=>r.schedule.mode==='AIR')).toHaveLength(10);expect(runs.filter(r=>r.schedule.mode==='SURFACE')).toHaveLength(21);expect(runs.filter(r=>r.schedule.mode==='RAIL')).toHaveLength(7);
for(const [mode,file,name] of [['AIR','06-air-visual','Aircraft'],['SURFACE','07-truck-visual','Truck'],['RAIL','07b-train-visual','Train']]){const run=runs.find(r=>r.schedule.mode===mode&&(mode==='RAIL'||r.schedule.origin_station==='CJBMB'));await page.locator('.operations-table tbody tr').filter({hasText:run.schedule.lane}).filter({hasText:run.schedule.service}).first().getByRole('button').first().click();await expect(page.getByRole('img',{name:name+' operational illustration'})).toBeVisible();await shot(file);await page.getByRole('button',{name:'Close details'}).click();}});
await check('Show all movements starts accelerated clock and moving markers',async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/operations/control-tower/playback'));await page.getByRole('button',{name:'Show All Movements'}).click();const result=await(await response).json();expect(result.playback_speed).toBe(600);expect(result.started.length).toBeGreaterThan(0);const before=(await api('/operations/control-tower/runs?service_date='+runs[0].service_date)).runs.find(r=>r.schedule_id==='surface-25');await new Promise(resolve=>setTimeout(resolve,3200));const after=(await api('/operations/control-tower/runs?service_date='+runs[0].service_date)).runs.find(r=>r.schedule_id==='surface-25');expect(after.movement.progress).toBeGreaterThan(before.movement.progress);expect(after.latest_location.latitude).not.toBe(before.latest_location.latitude);expect(after.elapsed_hours).toBeGreaterThan(before.elapsed_hours);await shot('08-moving-markers');results.push({name:'Playback evidence',pass:true,before:{progress:before.movement.progress,position:before.latest_location,elapsed:before.elapsed_hours,remaining:before.estimated_time_left_hours},after:{progress:after.movement.progress,position:after.latest_location,elapsed:after.elapsed_hours,remaining:after.estimated_time_left_hours}});});
await check('Azure normalized chat sequence with stale UDR selection',async()=>{const udr=runs.find(r=>r.schedule.origin_station==='UDRPU'&&r.schedule.gateway==='DELGW'&&r.schedule.mode==='SURFACE');await page.evaluate(async run=>{const {useControlTowerStore}=await import('/src/store/controlTowerStore.ts');useControlTowerStore.getState().select(run);},udr);await nav('AI Chat');const input=page.locator('.chat-panel textarea');async function send(message){await input.fill(message);const response=page.waitForResponse(r=>r.url().endsWith('/mcp-agent'),{timeout:30000});await input.press('Enter');const r=await(await response).json();expect(r.response).not.toContain('UDRPU');return r;}
const messages=['What services are available from CJBMB to BLRGW?','Show me the Air option.','Show me the Surface option.','What is the ETD and ETA of flight 6E 5355?','Which option arrives first?','Which vehicle is assigned to the Surface service from CJBMB to BLRGW?','What is its capacity?','Plan 2000 kg from CJBMB to BLRGW.','The vehicle assigned to the CJBMB-BLRGW Surface service has broken down. Find a replacement.','Delay the CJBMB-BLRGW Surface run by 30 minutes.','What happens if the shipment becomes 4000 kg?','Which available option can carry it?','Show the capacity and utilization calculation.','Which option from CJBMB to BLRGW is cheapest?'];
for(let i=0;i<messages.length;i++){const r=await send(messages[i]);results.push({name:'Chat turn '+(i+1),pass:true,normalization_source:r.normalization_source,response:r.response});if(i===0){expect(r.services).toHaveLength(2);await shot('09-cjb-service-lookup');}if(i===8){expect(r.recovery.replacement_vehicles).toHaveLength(0);await shot('11-breakdown-recovery');}if(i===9){expect(r.response).toContain('06:30 IST');await shot('12-surface-delay');}if(i===11){expect(r.response).toContain('NOT FEASIBLE');await shot('10-capacity-4000');}}});
await check('Chat closes on re-entering Planning and desktop overflow',async()=>{await nav('Planning');await expect(page.locator('.planning-chat-drawer')).toHaveCount(0);for(const width of [1600,1280]){await page.setViewportSize({width,height:950});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const a=await page.locator('.planning-left').boundingBox(),b=await page.locator('.planning-map').boundingBox();expect(b.x).toBeGreaterThan(a.x);expect(b.y).toBe(a.y);}});
await fs.writeFile(out+'/browser-results.json',JSON.stringify({results,errors},null,2));await browser.close();if(results.some(r=>!r.pass)||errors.length)process.exitCode=1;
