import {useEffect,useRef,useState,type CSSProperties,type ReactNode,type PointerEvent} from 'react';
import './DockableWorkspace.css';
export type DockPosition='left'|'right'|'top'|'bottom'|'floating';
type Rect={x:number;y:number;width:number;height:number};
type Layout={dockPosition:DockPosition;splitRatio:number;floating:Rect;lastDock:Exclude<DockPosition,'floating'>;isMaximized:boolean;previousLayout?:Omit<Layout,'previousLayout'>};
const positions:DockPosition[]=['left','right','top','bottom','floating'];
const limit=(n:number,a:number,b:number)=>Math.min(b,Math.max(a,n));
const finite=(v:unknown,fallback:number)=>typeof v==='number'&&Number.isFinite(v)?v:fallback;
export const defaultLayout=():Layout=>({dockPosition:'right',splitRatio:50,floating:{x:60,y:60,width:600,height:420},lastDock:'right',isMaximized:false});
export function boundFloating(rect:Rect,width:number,height:number):Rect{
 const w=limit(rect.width,Math.min(320,width),Math.max(1,width)),h=limit(rect.height,Math.min(280,height),Math.max(1,height));
 return {x:limit(rect.x,0,Math.max(0,width-w)),y:limit(rect.y,0,Math.max(0,height-h)),width:w,height:h};
}
export function readLayout(key:string):Layout{
 const d=defaultLayout();try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(!raw||!positions.includes(raw.dockPosition))return d;
 const clean=(v:any):Omit<Layout,'previousLayout'>=>({dockPosition:positions.includes(v.dockPosition)?v.dockPosition:'right',splitRatio:limit(finite(v.splitRatio,50),25,75),floating:{x:finite(v.floating?.x,60),y:finite(v.floating?.y,60),width:finite(v.floating?.width,600),height:finite(v.floating?.height,420)},lastDock:['left','right','top','bottom'].includes(v.lastDock)?v.lastDock:'right',isMaximized:!!v.isMaximized});
 return {...clean(raw),previousLayout:raw.previousLayout?clean(raw.previousLayout):undefined};}catch{return d;}
}
export function DockableWorkspace({primaryContent,mapContent,overlay,storageKey,label='planning'}:{primaryContent:ReactNode;mapContent:ReactNode;overlay?:ReactNode;storageKey:string;label?:string}){
 const root=useRef<HTMLDivElement>(null),[layout,setLayout]=useState(()=>readLayout(storageKey)),[size,setSize]=useState({width:1200,height:850});
 const drag=useRef<{kind:'move'|'split'|'resize';x:number;y:number;start:Layout;edge?:string;moved:boolean} |null>(null);
 const [preview,setPreview]=useState<DockPosition|null>(null),[dragging,setDragging]=useState(false);
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(layout));}catch{/* Layout still works without storage. */}},[layout,storageKey]);
 useEffect(()=>{const el=root.current;if(!el)return;const update=()=>{if(el.clientWidth&&el.clientHeight)setSize({width:el.clientWidth,height:el.clientHeight});};update();const observer=typeof ResizeObserver==='undefined'?null:new ResizeObserver(update);observer?.observe(el);window.addEventListener('resize',update);return()=>{observer?.disconnect();window.removeEventListener('resize',update);};},[]);
 const horizontal=layout.dockPosition==='left'||layout.dockPosition==='right';
 const extent=(horizontal?size.width:size.height)-8;
 const min= Math.min(45,Math.max(25,320/Math.max(1,extent)*100)),max=Math.max(55,Math.min(75,100-360/Math.max(1,extent)*100));
 const ratio=limit(layout.splitRatio,min,max),floating=boundFloating(layout.floating,size.width,size.height);
 const dock=(position:DockPosition)=>{setLayout(v=>({...v,dockPosition:position,lastDock:position==='floating'?v.lastDock:position,isMaximized:false,previousLayout:undefined}));setPreview(null);};
 const reset=()=>setLayout(defaultLayout());
 useEffect(()=>{const el=root.current;const restore=()=>setLayout(defaultLayout());el?.addEventListener('unifleet:reset-workspace',restore);return()=>el?.removeEventListener('unifleet:reset-workspace',restore);},[]);
 const maximize=()=>setLayout(v=>v.isMaximized?{...(v.previousLayout||v),isMaximized:false,previousLayout:undefined}:{...v,isMaximized:true,previousLayout:{dockPosition:v.dockPosition,splitRatio:v.splitRatio,floating:v.floating,lastDock:v.lastDock,isMaximized:false}});
 const target=(x:number,y:number):DockPosition|null=>{const box=root.current?.getBoundingClientRect();if(!box)return null;const px=(x-box.left)/box.width,py=(y-box.top)/box.height;if(px<0||py<0||px>1||py>1)return null;const sides=[['left',px],['right',1-px],['top',py],['bottom',1-py]] as const;const nearest=[...sides].sort((a,b)=>a[1]-b[1])[0];return nearest[1]<.27?nearest[0]:'floating';};
 const begin=(e:PointerEvent<HTMLElement>,kind:'move'|'split'|'resize',edge?:string)=>{if(e.button!==0)return;e.preventDefault();drag.current={kind,edge,x:e.clientX,y:e.clientY,start:{...layout,floating},moved:false};e.currentTarget.setPointerCapture(e.pointerId);};
 const move=(e:PointerEvent<HTMLElement>)=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>5)d.moved=true;
 if(d.kind==='move'&&d.moved){setDragging(true);setPreview(target(e.clientX,e.clientY));if(d.start.dockPosition==='floating'&&!d.start.isMaximized)setLayout(v=>({...v,floating:boundFloating({...d.start.floating,x:d.start.floating.x+dx,y:d.start.floating.y+dy},size.width,size.height)}));}
 if(d.kind==='split'){const box=root.current?.getBoundingClientRect();if(!box)return;const raw=horizontal?(e.clientX-box.left)/box.width*100:(e.clientY-box.top)/box.height*100;const next=layout.dockPosition==='right'||layout.dockPosition==='bottom'?100-raw:raw;setLayout(v=>({...v,splitRatio:limit(next,min,max)}));}
 if(d.kind==='resize'){const r=d.start.floating,edge=d.edge||'';const next={...r};if(edge.includes('e'))next.width+=dx;if(edge.includes('s'))next.height+=dy;if(edge.includes('w')){const change=Math.min(dx,r.width-Math.min(320,size.width));next.x+=change;next.width-=change;}if(edge.includes('n')){const change=Math.min(dy,r.height-Math.min(280,size.height));next.y+=change;next.height-=change;}setLayout(v=>({...v,floating:boundFloating(next,size.width,size.height)}));}
 };
 const end=(e:PointerEvent<HTMLElement>)=>{const d=drag.current;if(d?.kind==='move'&&d.moved){const position=target(e.clientX,e.clientY);if(position){if(position==='floating'&&d.start.dockPosition!=='floating'){const box=root.current!.getBoundingClientRect();setLayout(v=>({...v,dockPosition:'floating',isMaximized:false,previousLayout:undefined,floating:boundFloating({...v.floating,x:e.clientX-box.left-v.floating.width/2,y:e.clientY-box.top-20},size.width,size.height)}));}else dock(position);}}drag.current=null;setDragging(false);setPreview(null);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);};
 const cancel=()=>{drag.current=null;setDragging(false);setPreview(null);};
 const events={onPointerMove:move,onPointerUp:end,onPointerCancel:cancel};
 const grid:CSSProperties=layout.isMaximized?{gridTemplateAreas:'"map"',gridTemplateColumns:'minmax(0,1fr)',gridTemplateRows:'minmax(0,1fr)'}:layout.dockPosition==='floating'?{gridTemplateAreas:'"primary"',gridTemplateColumns:'minmax(0,1fr)',gridTemplateRows:'minmax(0,1fr)'}:horizontal?{gridTemplateAreas:layout.dockPosition==='left'?'"map split primary"':'"primary split map"',gridTemplateColumns:layout.dockPosition==='left'?`${ratio}fr 8px ${100-ratio}fr`:`${100-ratio}fr 8px ${ratio}fr`,gridTemplateRows:'minmax(0,1fr)'}:{gridTemplateAreas:layout.dockPosition==='top'?'"map" "split" "primary"':'"primary" "split" "map"',gridTemplateColumns:'minmax(0,1fr)',gridTemplateRows:layout.dockPosition==='top'?`${ratio}fr 8px ${100-ratio}fr`:`${100-ratio}fr 8px ${ratio}fr`};
 const mapStyle:CSSProperties=layout.dockPosition==='floating'&&!layout.isMaximized?{position:'absolute',left:floating.x,top:floating.y,width:floating.width,height:floating.height}:{};
 return <div ref={root} className={`planning-split workspace-split dockable-workspace dock-${layout.dockPosition} ${layout.isMaximized?'dock-maximized':''} ${dragging?'dock-dragging':''}`} style={grid} data-dock-position={layout.dockPosition} data-maximized={layout.isMaximized}>
  <div className="planning-left workspace-content dock-primary" hidden={layout.isMaximized}>{primaryContent}{overlay}</div>
  <div className="planning-divider dock-splitter" hidden={layout.isMaximized||layout.dockPosition==='floating'} role="separator" aria-label={`Resize ${label} and map`} aria-orientation={horizontal?'vertical':'horizontal'} aria-valuemin={Math.round(min)} aria-valuemax={Math.round(max)} aria-valuenow={Math.round(ratio)} tabIndex={0} onPointerDown={e=>begin(e,'split')} {...events} onDoubleClick={()=>setLayout(v=>({...v,splitRatio:50}))} onKeyDown={e=>{if(e.key==='Home')setLayout(v=>({...v,splitRatio:50}));if(['ArrowLeft','ArrowUp','ArrowRight','ArrowDown'].includes(e.key))setLayout(v=>({...v,splitRatio:limit(v.splitRatio+(['ArrowLeft','ArrowUp'].includes(e.key)?-2:2)*(layout.dockPosition==='right'||layout.dockPosition==='bottom'?-1:1),min,max)}));if(e.key==='Home'||e.key.startsWith('Arrow'))e.preventDefault();}}/>
  <section className="planning-map workspace-map dock-map-panel" style={mapStyle} aria-label="Map panel">
   <header className="dock-map-header" onDoubleClick={e=>{if(!(e.target as HTMLElement).closest('button,summary'))maximize();}}>
    <div className="dock-map-grab" role="button" tabIndex={0} aria-label="Move map panel" title="Drag to dock the map, or use the layout menu" onPointerDown={e=>begin(e,'move')} {...events} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();root.current?.querySelector<HTMLDetailsElement>('.dock-map-menu')?.setAttribute('open','');root.current?.querySelector<HTMLButtonElement>('.dock-map-menu button')?.focus();}}}><svg viewBox="0 0 16 20" width="13" height="18" aria-hidden="true">{[5,11].flatMap(x=>[4,10,16].map(y=><circle key={`${x}-${y}`} cx={x} cy={y} r="1.2" fill="currentColor"/>))}</svg><strong>Map</strong><span>{layout.isMaximized?'Focused':layout.dockPosition}</span></div>
    <div className="dock-map-actions"><button title="Fit to selected routes or current network" aria-label="Fit to selected" onClick={()=>root.current?.dispatchEvent(new CustomEvent('unifleet:fit-map'))}>Fit</button><button title={layout.isMaximized?'Restore previous layout':'Focus map'} aria-label={layout.isMaximized?'Restore map':'Expand map'} onClick={maximize}>{layout.isMaximized?'Restore':'Expand'}</button>{layout.dockPosition==='floating'&&!layout.isMaximized&&<button title="Return map to its previous dock" onClick={()=>dock(layout.lastDock)}>Dock</button>}<details className="dock-map-menu"><summary title="Map docking and layout options" aria-label="Map layout menu">⋮</summary><div role="group" aria-label="Map docking options">{positions.map(position=><button key={position} aria-pressed={layout.dockPosition===position} onClick={e=>{dock(position);e.currentTarget.closest('details')?.removeAttribute('open');}}>Dock {position}</button>)}<button onClick={e=>{reset();e.currentTarget.closest('details')?.removeAttribute('open');}}>Reset layout</button></div></details></div>
   </header>
   <div className="workspace-map-canvas dock-map-body">{mapContent}</div>
   {layout.dockPosition==='floating'&&!layout.isMaximized&&['n','s','e','w','ne','nw','se','sw'].map(edge=><div key={edge} className={`floating-resize resize-${edge}`} role="separator" aria-label={`Resize floating map ${edge}`} aria-orientation={edge==='n'||edge==='s'?'horizontal':'vertical'} tabIndex={0} onPointerDown={e=>begin(e,'resize',edge)} {...events} onKeyDown={e=>{if(e.key.startsWith('Arrow')){e.preventDefault();setLayout(v=>({...v,floating:boundFloating({...v.floating,width:v.floating.width+(['ArrowRight'].includes(e.key)?20:e.key==='ArrowLeft'?-20:0),height:v.floating.height+(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0)},size.width,size.height)}));}}}/>)}
  </section>
  {dragging&&<div className="dock-drop-overlay" aria-label="Map docking targets"><div className={`dock-preview preview-${preview||'none'}`}/>{positions.map(position=><div key={position} className={`dock-target target-${position} ${preview===position?'active':''}`}>{position==='floating'?'Float':position.charAt(0).toUpperCase()+position.slice(1)}</div>)}</div>}
 </div>;
}
